language: cpp

os:
  - linux
  - osx

dist:
  - trusty

compiler:
  - clang
  - gcc

env:
  global:
    - BUILD_TYPE=Release

matrix:
  exclude:
    # Don't compile with gcc on MacOS
    - os: osx
      compiler: gcc

before_script:
  - git clone https://github.com/themoos/core-moos.git core-moos
  - cd core-moos
  - mkdir moos-build
  - cd moos-build
  - cmake -DCMAKE_INSTALL_PREFIX=install_dir -DENABLE_EXPORT=ON -DUSE_ASYNC_COMMS=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON -DUSE_CXX11_IF_AVAILABLE=ON ..
  - cmake --build . --config Release -- -j3
  - cmake --build . --config Release --target install
  - cd ../..
  - mkdir build/

script:
  - cd build/
  - cmake -DCMAKE_INSTALL_PREFIX=install_dir -DENABLE_EXPORT=ON -DUSE_ASYNC_COMMS=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -DUSE_CXX11_IF_AVAILABLE=$USE_CXX11_IF_AVAILABLE ..
  - cmake --build . --config Release -- -j3
  - cmake --build . --config Release --target install
